[project]
name = 'btc-oracle-sec-layer'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bitcoin-oracle-core]
path = 'contracts/bitcoin-oracle-core.clar'
clarity_version = 3
epoch = 3.1

[contracts.bitcoin-oracle-storage]
path = 'contracts/bitcoin-oracle-storage.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
